### ISSUE TITLE
Possible to grab data from specific weather stations

### ISSUE THREAD

**Issue by GatoPharaoh** [naofireblade/homebridge-weather-station-extended#1]
Hi

is it possible to grab the data from specific weather stations?
if you visit the weather overview of a city and scroll all the way down you can see weather stations located in that city and all of it's data

Every single station has a unique ID e.g. ICALIFORN123

Would it be possible to grab the data just from a specific station instead of the whole city?

thank you in advance

**Comment by GatoPharaoh** [comment]
got it - for anyone else:
take the PWS of the weather station e.g. ICALIFOR123
got to your config.json and put under location: [pws:ICALIFOR123](url)

**Comment by naofireblade** [comment]
Nice find, i will add that to the readme.

**Comment by naofireblade** [comment]
I added the information to the readme. Thanks for finding out :) .
