### ISSUE TITLE
Impossible to configure config.json

### ISSUE THREAD

**Issue by Solusan** [naofireblade/homebridge-weather-station-extended#15]
Hello,

I need to assign a different area than the example:

`       {
                "platform": "WeatherStation",
                "name": "Weather Station",
                "key": "XXXXXXXXXXXXXX",
                "location": "78613"
        }`

I tried to assign longitude and latitude but, I cannot see how can I do it.

May I ask you about ho can be the right syntax?

Many thanks in advance.

**Comment by naofireblade** [comment]
Hi, sadly this is not possible with the underlying weatherunderground api. But you can enter you geo data here in the search bar: https://www.wunderground.com/
Open the result and click on "change" to look for the nearest weather station. Then just copy the last part of the url into the homebridge configuration and add "pws:" in front of it.
e.g. "pws:KCASANFR1156"

**Comment by Solusan** [comment]
Hi, It works.

I don't know how accurate is but it works more or less.

Thanks a lot for your work! 👍

**Comment by naofireblade** [comment]
You are welcome.
