### ISSUE TITLE
new plug-in inspired by this one

### ISSUE THREAD

**Issue by bbernstein** [naofireblade/homebridge-weather-station-extended#16]
I created a new plug-in to be a single-purpose homebridge plug-in for turning on and off snow-melting mats. It was inspired by this project but I removed most of the features to make it a simple switch that looks for impending snow.

I gave credit to this plug-in and wanted to give you a shout-out for the excellent work. My original thought was to fork and extend this plug-in but then thought the audience for it would be fairly niche and they would not necessarily need the full set of features. Also, I wanted it to be a simple switch that could trigger the single action rather than needing to add additional virtual switches to trigger checking the values of the weather.

The new plug-in is called [homebridge-snowswitch](https://www.npmjs.com/package/homebridge-snowswitch) which is a simple switch that goes on and off depending on the snow forecast and current conditions.

Thanks for your great plug-in and inspiration.

**Comment by naofireblade** [comment]
Hey bbernstein,

thanks for your kind words and the attribution :) . Your plugin covers an interesting use-case. I didn't even know these mats exist.

Best regards
Arne
