### ISSUE TITLE
[enhancement] Temperature profile with Elgato Eve App (FakeGato support)

### ISSUE THREAD

**Issue by DJay-X** [naofireblade/homebridge-weather-station-extended#17]
@naofireblade Again thanks for your great work, sharing it and the ongoing development.
Any news about planning the recorded History to show up in Eve App?
Temperature profile with Elgato Eve App (FakeGato support)
https://github.com/simont77/fakegato-history

**Comment by naofireblade** [comment]
Hey I really would like to implement that. Sadly I don't have time for that at the moment. Maybe in the upcoming month.

**Comment by naofireblade** [comment]
Nevermind, it's actually pretty easy and I will release an update soon.

**Comment by naofireblade** [comment]
I updated the index.js to include the history service (not yet published to npm). You can try it by downloading the index.js and replacing your local one.

Sadly the eve app has a bug with device informations that contain a „/„ . I fixed that but the eve app must be uninstalled and reinstalled to get the history working.

Then you will get new history entries every 10 minutes.

**Comment by naofireblade** [comment]
Added in version 1.2.0.
