### ISSUE TITLE
No graph data

### ISSUE THREAD

**Issue by tomsteenbakkers** [naofireblade/homebridge-weather-station-extended#20]
I have updated the plugin and uninstalled the eve app and reinstalled it to see the graphs. But, unfortunately, no graph data is shown. Is there another way to enable this?

**Comment by naofireblade** [comment]
The first points of the graph should appear after 10-30 minutes after starting homebridge. When you open the details of the empty graph, do you see entries in the measurements list?
Did you set any interval in the plugin? Or do you use the default one of 4 minutes?

Can you start homebridge with the debug option for my plugin and post the output?
`sudo DEBUG=homebridge-weather-station-extended homebridge -D -U /var/lib/homebridge`
/var/lib/homebridge is my homebridge folder, it might be different depending on your installation. If you are running homebridge as a service, you can either change your start options or stop the service and start homebridge manually with the given example command.

**Comment by tomsteenbakkers** [comment]
- opening the empty graph and looking at measurements, no data is shown
- I set the interval to 15 min. Now, I have set is to 4 min and did a reboot, log will be created now

I will post the log when it is running for 30 min. Where can I find the log when I start Homebridge with the syntax you provided.

**Comment by naofireblade** [comment]
If you start homebridge with the command, the log will be in your console. If you start homebridge as a service the log should be a part of /var/log/syslog

**Comment by tomsteenbakkers** [comment]
@naofireblade 

Enclosed the logfile
[log2.txt](https://github.com/naofireblade/homebridge-weather-station-extended/files/1708923/log2.txt)

**Comment by naofireblade** [comment]
Thanks for your log. I can see that the history module is starting and that 2 datasets are added. But I can't see any request for the history.
Can you provide another log where you close, and reopen the eve app and select the history for e.g. temperature? Homebridge must be running for at least 20 minutes before that.

**Comment by tomsteenbakkers** [comment]
@naofireblade Enclosed the log file. I can see new entries in de chart. Every 10 min an entry is logged using the DEBUG method. After I restart the Pi the logging stops. The difference is that after the restart Homebridge starts using systemd. 

note: I see this only history on the iPhone not on the iPad.

[log_2018-02-09.txt](https://github.com/naofireblade/homebridge-weather-station-extended/files/1710158/log_2018-02-09.txt)

**Comment by tomsteenbakkers** [comment]
@naofireblade after running Homebridge in debug mode for several hours I stopped the program and started using systemd again. I made one adjustment by setting the debug mode on. It’s running now for 8 hours and all the graphs are recording measurements. Also the graphs for the evohome plugin.

**Comment by naofireblade** [comment]
Hm so it's working now? Also with systemd? The debug mode cannot be the reason.

**Comment by tomsteenbakkers** [comment]
It’s working now. I also use the evohome plugin and I did have the same problems with the graphs. On the iPad I can see the graphs with measurements for the last 24 hours. On the iPhone and still have empty timeframes. 

Ps. I did close the eve app several times during logging. And also did some forced refresh. Let’s hope is stays this way 😇

**Comment by tomsteenbakkers** [comment]
One last thing: can you explain why the iPhone is missing data in certain timeframes while the iPad shows data in the same interval.

**Comment by awein** [comment]
I came across problems around this as well. This plugin will set the global timer interval for FakeGatoHistory to 4032 minutes. This may affect other plugins as well since this timer will be shared across different plugins. This timer needs to fire to update the history entries and write the history to the filesystem (new feature of version 0.4.0).

https://github.com/naofireblade/homebridge-weather-station-extended/blob/cf38245b12e58f8d601f664f227d6350a3d8cb6f/index.js#L433

I updated the FakeGatoHistory package to 0.4.0 and replaced the line above with:
```
this.historyService = new FakeGatoHistoryService("weather", this, {
  storage: 'fs'
});
```

This resolved the issue of missing history data and added support for the new history persistence feature.

**Comment by naofireblade** [comment]
@awein The number ist the max amount of frames, not the interval. I will try to update to the recent fakegato package on the weekend :) .

@tomsteenbakkers The gaps happen when you restart homebridge before pulling the history on all your devices. After a restart homebridge currently no longer knows the old history data and can't provide it to devices that didn't pulled the history yet. This will be solved in the next update when i integrate the new fakegator release.

**Comment by naofireblade** [comment]
I'll close this as your initial problem is solved. If you have any other questions please don't hesitate creating a new issue.
