### ISSUE TITLE
Eve weather data gaps

### ISSUE THREAD

**Issue by albi** [naofireblade/homebridge-weather-station-extended#21]
Sometimes there are gaps in the history of the temperature, airpressure and humidity. Is there something I can do about it? Is the data stored on the iOS device or inside of homebridge?

**Comment by albi** [comment]
Now I see how it works. I think restarting homebridge without having opened the Eve app is not a good idea. Can you confirm this?

**Comment by naofireblade** [comment]
Yes sorry for the late answer. After a restart homebridge no longer holds the history. This will be fixed with the upcoming update :) .

**Comment by albi** [comment]
nice. waitig for it and syncing each time before restarting until the update brings the feature! :)
