### ISSUE TITLE
Eve history sometimes won't update

### ISSUE THREAD

**Issue by albi** [naofireblade/homebridge-weather-station-extended#23]
My last issue was closed by myself regarding the history inside the Eve app.  But now I've discovered that sometimes Eve won't update anymore until I delete and reinstall the app. After that all the history is gone and I have to go through all the reconfiguring inside the app hassle again. Do you have the same issue sometimes? It is very strange  I can't see a pattern when this happens. Now this has just happened on my iPhone, while my iPad is reading the history as expected.

**Comment by naofireblade** [comment]
Sorry to hear that. I didn't experienced such behavior yet. If it does not update next time, can you force close the app, start homebridge in debug mode, re-open the app and try to pull and update? That log should be helpful to see if anything goes wrong with pulling the history.

**Comment by albi** [comment]
here is something from the debug log, does it help you?



`homebridge-weather-station-extended Update weather online +3m
  homebridge-weather-station-extended Update values for Now +254ms
[2018-2-22 08:01:12] [WU] **Fakegato-timer: addData  Now { time: 1519282872.407, temp: -3.7, pressure: 1011, humidity: 88 }  immediate:  false
  homebridge-weather-station-extended Update values for Today +8ms
  homebridge-weather-station-extended Update values for In 1 Day +4ms
  homebridge-weather-station-extended Update values for In 2 Days +3ms
  homebridge-weather-station-extended Update values for In 3 Days +3ms
`

**Comment by naofireblade** [comment]
Thats just the plugin updating the weather and saving it to the history cache in homebridge. I need the log when your device (iPhone) tries to pull that history from homebridge (without success).

**Comment by albi** [comment]
I'll have a try…

**Comment by albi** [comment]
After restarting the RasPi everything is back to normal. If this issue comes back again, I'll go for the debug log.

**Comment by naofireblade** [comment]
You don't need to restart the RasPi. Just keep homebridge running in debug mode and when the problem occurs:
1. Force close the eve app
2. Re-Open the eve app
3. Pull the history in the eve app
4. Provide the log from step 1 to 3.

**Comment by albi** [comment]
Had to restart because of other reasons ;)

**Comment by naofireblade** [comment]
Valid point :D . Just wanted to make sure you don't solve the error by restarting before you can log it.

**Comment by albi** [comment]
Awesome update the last weekend! All data is now persistent. My strange bug seems to be gone! Kudos!

**Comment by naofireblade** [comment]
Great to hear. Have fun :)
