### ISSUE TITLE
Type: Sensor

### ISSUE THREAD

**Issue by Xaositek** [naofireblade/homebridge-weather-station-extended#27]
Would it be possible to have homebridge-weather-station-extended introduce the data as Sensors which would allow direct usage of Automation in the Home app?

Perhaps this is not the intended usage of sensors and highly frowned upon.

**Comment by naofireblade** [comment]
The Home app from Apple only supports a very limited sets of weather sensors (temperature and humidity). Therefore I created custom sensor types. You can use them and create automations based on them with 3rd party homekit apps like [Elgato Eve](https://itunes.apple.com/de/app/elgato-eve/id917695792?mt=8) or [Home](https://itunes.apple.com/de/app/home-hausautomatisierung/id995994352?mt=8)
