### ISSUE TITLE
plugin installed, but homebridge not recognizing it.

### ISSUE THREAD

**Issue by ikonis** [naofireblade/homebridge-weather-station-extended#3]
I'm getting the plugin as not registered now, it is probably a stupid problem on my part, but I cannot for the life of me figure it out.
Here is the log:

Sep 05 07:48:51 raspberrypi homebridge[2989]: /usr/local/lib/node_modules/homebridge/lib/api.js:64
Sep 05 07:48:51 raspberrypi homebridge[2989]: throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
Sep 05 07:48:51 raspberrypi homebridge[2989]: ^
Sep 05 07:48:51 raspberrypi homebridge[2799]: Error: The requested accessory 'WUWeatherStationExtended' was not registered by any plugin.
Sep 05 07:48:51 raspberrypi homebridge[2799]: at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:254:42)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Module._compile (module.js:571:32)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Object.Module._extensions..js (module.js:580:10)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Module.load (module.js:488:32)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at tryModuleLoad (module.js:447:12)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Function.Module._load (module.js:439:3)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at Module.runMain (module.js:605:10)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at run (bootstrap_node.js:425:7)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at startup (bootstrap_node.js:146:9)
Sep 05 07:48:51 raspberrypi homebridge[2799]: at bootstrap_node.js:540:3
Sep 05 07:48:51 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Sep 05 07:48:51 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

and requisite part of the config

>
      {
        "accessory": "WUWeatherStationExtended",
        "name": "Weather Station",
        "interval": "4",
        "key": "xxxxxxxxxxxxxxx",
        "location": "pws:KTXTYLER51",
        "forecast": "today"
      }

**Comment by naofireblade** [comment]
Im sorry, I had an error in the config part of the readme. I already published a new version with the correct readme.

Your config should look like this and must be in the platforms part. The parameters vor interval and forecast are optional, you can delete them if you want. With your current config you would get the forecast only for today.

`
    {
        "platform": "WeatherStation",
        "name": "Weather Station",
        "interval": "4",
        "key": "XXXXXXXXXXXXXXX",
        "location": "pws:KTXTYLER51",
        "forecast": "today"
    }
`

Please tell me if its working for you now.

**Comment by ikonis** [comment]
Finally had a chance to do the change. 
Works perfectly. Cheers to an excellent update.

**Comment by naofireblade** [comment]
Thanks for your feedback.
