### ISSUE TITLE
Error getting Temperature

### ISSUE THREAD

**Issue by lfiocco** [naofireblade/homebridge-weather-station-extended#4]
I loaded the app, I set the forecast for 3days. I see all the parameters, I only see temperature NOW. 
I do  see parameters for everything else. In Homekit app from apple I also get "No Response" on forecast days. But when I access the data from another app, I do see information there. 

Temperature for forecast days displays error. everything else works.

Also it seems to give the "No Response" on other devices on the same page. But when I tap on them they come online.

**Comment by naofireblade** [comment]
Hi lfiocco,
i see 2 problems here (correct me if I'm wrong).

1. The apple Homekit app does not show other parameters then temperature. Thats a constraint of the apple Homekit app. Therefore i recommend using of Eve or other Homekit apps that support custom characteristics.
2. You have sporadic "no response" issues. This might happen because you changed the configuration for the forecast. Apple does not handle it well when a device (my homebrige plugin) changes his services (each forecast day is a service) during runtime. Please try the following workaround and tell me if it works:

Remove my plugin from your homebridge config. Restart homebridge. Open any homekit app. Add my plugin to your homebridge config. Restart homebridge. Open any homekit app.

**Comment by lfiocco** [comment]
Sorry if explanation was not clear I am using a different home app the one that cost $20.99 it displays the forecast for three days all the information is all there except that current temperature or the forecast temperature it is the only parameter missing

Sent from my iPad

On Sep 19, 2017, at 10:05 AM, Arne <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi lfiocco,
i see 2 problems here (correct me if I'm wrong).

  1.  The apple Homekit app does not show other parameters then temperature. Thats a constraint of the apple Homekit app. Therefore i recommend using of Eve or other Homekit apps that support custom characteristics.
  2.  You have sporadic "no response" issues. This might happen because you changed the configuration for the forecast. Apple does not handle it well when a device (my homebrige plugin) changes his services (each forecast day is a service) during runtime. Please try the following workaround and tell me if it works:

Remove my plugin from your homebridge config. Restart homebridge. Open any homekit app. Add my plugin to your homebridge config. Restart homebridge. Open any homekit app.

**Comment by naofireblade** [comment]
Ok, I tested my plugin successful with these two 3rd party apps:
- https://itunes.apple.com/de/app/home-einfache-hausautomatisierung/id995994352?mt=8
- https://itunes.apple.com/de/app/elgato-eve/id917695792?mt=8 (free)

Can you send me a link to your app?

You could also write the author of your app and tell him this description of how my app works with homekit:

- Each day is an accessory. Each accessory has exact one service. This is the homekit "TemperatureSensor" service.
- And the service has the homekit characteristic "CurrentTemperature" (that's the one you cannot see).
- I also added some custom characteristics to this service for each day (that are the ones u can see).
So his app handles custom characteristics pretty well but doesn't show the default characteristic when the service is extended by custom characteristics.

By the way. I do this, so you can at least see the temperature in apples home app and have a nice temperature icon in other apps.

**Comment by lfiocco** [comment]
Here are some screenshots of what I see I am using this application on raspberry pi 3

I am using the first application in your links

[image1.png]


[image2.png]

[image3.png]
Sent from my iPhone

On Sep 20, 2017, at 1:13 PM, Arne <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I tested my plugin successful with these two 3rd party apps:

  *   https://itunes.apple.com/de/app/home-einfache-hausautomatisierung/id995994352?mt=8
  *   https://itunes.apple.com/de/app/elgato-eve/id917695792?mt=8 (free)

Can you send me a link to your app?

You could also write the author of your app and tell him this description of how my app works with homekit:

  *   Each day is an accessory. Each accessory has exact one service. This is the homekit "TemperatureSensor" service.
  *   And the service has the homekit characteristic "CurrentTemperature" (that's the one you cannot see).
  *   I also added some custom characteristics to this service for each day (that are the ones u can see).
So his app handles custom characteristics pretty well but doesn't show the default characteristic when the service is extended by custom characteristics.

By the way. I do this, so you can at least see the temperature in apples home app and have a nice temperature icon in other apps.

**Comment by naofireblade** [comment]
Images are sadly not included in github. Can you upload them at imgur or something like that?
This is how the app looks for me. In both views I can see the temperature:
## All 5 Days
![All 5 Days](https://i.imgur.com/oCcCQ5I.jpg)
## Single Day
![Single Day](https://i.imgur.com/Pmqz2CE.png)

**Comment by lfiocco** [comment]
I fixed the problem, it was on my part. Not the plugin. After I cleaned it, I reinstalled it. No more problems. Thanks for you great work and help.

**Comment by naofireblade** [comment]
Great to hear that.
