### ISSUE TITLE
Temperature Forecast

### ISSUE THREAD

**Issue by DSchumacher2104** [naofireblade/homebridge-weather-station-extended#5]
Is it possible to add minimum temperature forecast? The plugin only shows maximum temperature forecast. I want to use the plugin for indicating frost forecast.

**Comment by naofireblade** [comment]
Sure, I will look into this in the upcoming week.

**Comment by naofireblade** [comment]
Here you go: [Version 1.1.0]( https://github.com/naofireblade/homebridge-weather-station-extended/releases/tag/v1.1.0)

You can update the plugin with `sudo npm update -g homebridge-weather-station-extended`
