### ISSUE TITLE
Negative temperature

### ISSUE THREAD

**Issue by m017893-1** [naofireblade/homebridge-weather-station-extended#6]
Hi, this seams à recurring problem from other packages.

The negatives temperature values are showed as 0. On the northern regions the temperature is currently negative specially showed in celsius.

Other have fixes fixes this by changing the minimum value to -100 to force homekit to accept it.
While creating the accessories. 

Can this be done here ?

Regards

**Comment by naofireblade** [comment]
Hi, good find. The minValue for the temperature characteristic in HAP is 0. I will override this as you suggested.

**Comment by IMNotMax** [comment]
I have the same problem :) All temperatures are showed as 0, currently -3 celcius

**Comment by naofireblade** [comment]
I'm working on it :) and will update the app soon.

**Comment by naofireblade** [comment]
Fixed in version 1.1.1.

Thanks for revealing the bug and suggesting a solution.

**Comment by m017893-1** [comment]
Thanks for your fast action. It is working like a charm.

Regards, Michel

**Comment by IMNotMax** [comment]
Yes !!! This is great ! Thanx
