### ISSUE TITLE
How do I get anything but temperature

### ISSUE THREAD

**Issue by tomwoodhams** [naofireblade/homebridge-weather-station-extended#7]
Its installed as described, I get my forecasts in Homekit which is great.
But its just showing temperature, I want to have the other observations like rain today etc.
Where am I going wrong?

**Comment by naofireblade** [comment]
Hey, you need to download an homekit app that supports custom characteristics (rain etc.) like Elgato Eve.

**Comment by tomwoodhams** [comment]
Ah, got it - downloading Eve. thanks for your help.

**Comment by naofireblade** [comment]
You're welcome.
