### ISSUE TITLE
Exposing more than temperature to Homekit

### ISSUE THREAD

**Issue by BuckarooToo** [naofireblade/homebridge-weather-station-extended#8]
Even using Elgato's Eve, I am only seeing the daily high temperatures. I would like to see current conditions as well (planning to turn on my roof cables if it is snowing). I'm guessing this involves updating the config.json file, but I'm not sure if I'm to add accessories, or if more lines are needed in the platform section. Please help!

**Comment by naofireblade** [comment]
Hi BuckarooToo,

did you use the simple configuration from the readme? That should give you 5 devices in the Eve app (Now, Today, In 1 day, In 2 days, In 3 days). Each one can be **opened** with a tap and has a lot of weather parameters.

**Comment by BuckarooToo** [comment]
Aha! Now I see them! I can get to them in a couple of apps, including Eve and Home (by Matthias Hochgatter), though not in the details of Apple's Home app.

Thanks!

**Comment by naofireblade** [comment]
You're welcome.
