### ISSUE TITLE
Localization options

### ISSUE THREAD

**Issue by m-rossi** [naofireblade/homebridge-weather-station-extended#9]
Maybe it is possible add some localization options for the current observations "now" and the forecast "Today", "In 1 Day", "In 2 Days" and "In 3 Days"?

**Comment by naofireblade** [comment]
Do you mean translations of the device names (e.g. Today) or a conversion to imperial units?

The device names can be renamed manually.

**Comment by m-rossi** [comment]
Yes, it would ne nice to have (in my case) german device name. By renaming the device you mean inside the Home App, right?

**Comment by naofireblade** [comment]
Yes you can rename "Today" etc. in any homekit app. 
Renaming of characeristics (e.g. Wind speed) is not possible. Translating is also not possible for me. This has to be done by the app itself.
Temperature and Humidity are known homekit characteristics so these are translated in most apps. But all the other characteristics are created by me and so far only the developers of the Elgato Eve app took the effort to translate them.

**Comment by m-rossi** [comment]
Ok, thanks. I will rename it in the app.
